// weaponDatabase.js

// Weapon database with all stats
const weapons = {
  // top-level list of stratagems granted to all players (not selectable picks)
  grantedStratagems: [
    { name: "Resupply", warbond: "free", slot: "none", defaultGranted: true, notes: "Granted to all players" },
    { name: "Reinforce", warbond: "free", slot: "none", defaultGranted: true, notes: "Granted to all players" },
    { name: "Hellbomb", warbond: "free", slot: "none", defaultGranted: true, notes: "Granted to all players" },
    { name: "SEAF Artillery", warbond: "free", slot: "none", defaultGranted: true, notes: "Granted to all players" }
  ],
  primary: [
        // Free/Base Game
        { name: "AR-23 Liberator", warbond: "free", type: "Assault Rifle",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "AR-23P Liberator Penetrator", warbond: "free", type: "Assault Rifle",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
        { name: "SG-225 Breaker", warbond: "free", type: "Shotgun",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "SG-8 Punisher", warbond: "free", type: "Shotgun",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
        { name: "R-63 Diligence", warbond: "free", type: "Marksman Rifle",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "R-63CS Diligence Counter Sniper", warbond: "free", type: "Marksman Rifle",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
        { name: "SMG-37 Defender", warbond: "free", type: "Submachine Gun",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "SG-225SP Breaker Spray&Pray", warbond: "free", type: "Shotgun",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "SG-8S Slugger", warbond: "free", type: "Shotgun",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "Plas-1 Scorcher", warbond: "free", type: "Energy-Based",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "Las-5 Scythe", warbond: "free", type: "Energy-Based",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "R-2124 Constitution", warbond: "free", type: "Marksman Rifle",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
        { name: "MP-98 Knight", warbond: "free", type: "Submachine Gun",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        
        // Steeled Veterans
        { name: "AR-23C Liberator Concussive", warbond: "steeled-veterans", type: "Assault Rifle",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
        { name: "SG-225IE Breaker Incendiary", warbond: "steeled-veterans", type: "Shotgun",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
        { name: "Jar-5 Dominator", warbond: "steeled-veterans", type: "Explosive",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
          
        // Cutting Edge
        { name: "Las-16 Sickle", warbond: "cutting-edge", type: "Energy-Based",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "SG-8P Punisher Plasma", warbond: "cutting-edge", type: "Energy-Based",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "ARC-12 Blitzer", warbond: "cutting-edge", type: "Energy-Based",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Democratic Detonation
        { name: "R-36 Eruptor", warbond: "democratic-detonation", type: "Explosive",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "CB-9 Exploding Crossbow", warbond: "democratic-detonation", type: "Explosive",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "BR-14 Adjudicator", warbond: "democratic-detonation", type: "Assault Rifle",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
          
        // Polar Patriots
        { name: "AR-16 Tenderiser", warbond: "polar-patriots", type: "Assault Rifle",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "Plas-101 Purifier", warbond: "polar-patriots", type: "Energy-Based",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "SMG-72 Pummeller", warbond: "polar-patriots", type: "Submachine Gun",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Viper Commandos
        { name: "AR-23A Liberator Carbine", warbond: "viper-commandos", type: "Assault Rifle",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Freedom's Flame
        { name: "SG-451 Cookout", warbond: "freedom-flame", type: "Shotgun",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
        { name: "Flam-66 Torcher", warbond: "freedom-flame", type: "Special",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
          
        // Truth Enforcers
  { name: "SMG-32 Reprimand", warbond: "truth-enforcers", type: "Submachine Gun",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
  { name: "SG-20 Halt", warbond: "truth-enforcers", type: "Shotgun",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Servants of Freedom
  { name: "Las-17 Double-Edge Sickle", warbond: "servants-freedom", type: "Energy-Based",
          light: "green", medium: "green", heavy: "green",
          bugnest: "red", charger: "yellow", biletitan: "yellow",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
          
        // Masters of Ceremony
  { name: "R-2 Amendment", warbond: "masters-ceremony", type: "Marksman Rifle",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Control Group Premium Warbond - Placeholder entries (details TBD)
  { name: "VG-70 Variable", warbond: "control-group", type: "Special",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "red",
          warpship: "green", harvester: "red", voteless: "yellow" },
        
        // ODST Legendary Warbond (Halo Crossover - 1,500 SC)
  { name: "MA5C Assault Rifle", warbond: "odst", type: "Assault Rifle",
          light: "green", medium: "green", heavy: "yellow",
          bugnest: "yellow", charger: "green", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "green",
          warpship: "green", harvester: "yellow", voteless: "green" },
  { name: "M7S SMG", warbond: "odst", type: "Submachine Gun",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "yellow", hulk: "red", strider: "red",
          warpship: "yellow", harvester: "red", voteless: "green" },
  { name: "M90A Shotgun", warbond: "odst", type: "Shotgun",
          light: "green", medium: "green", heavy: "yellow",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "yellow" },
        
        // Dust Devils Premium Warbond - Placeholder entries (details TBD)
  // Removed Dust Devil placeholder primary; replaced with concrete entries above (AR-2 Coyote, etc.)
          
    // Borderline Justice
  { name: "R-6 Deadeye", warbond: "borderline-justice", type: "Marksman Rifle",
      light: "green", medium: "green", heavy: "red",
      bugnest: "red", charger: "yellow", biletitan: "red",
      factory: "red", hulk: "yellow", strider: "yellow",
      warpship: "red", harvester: "yellow", voteless: "green" },

    // Force of Law Premium Warbond - Page additions
  { name: "AR-32 Pacifier", warbond: "force-of-law", type: "Assault Rifle",
      light: "green", medium: "green", heavy: "red",
      bugnest: "red", charger: "yellow", biletitan: "red",
      factory: "red", hulk: "yellow", strider: "yellow",
      warpship: "red", harvester: "yellow", voteless: "green" }
    ],
    secondary: [
        // Free/Base Game
  { name: "P-2 Peacemaker", warbond: "free", type: "Pistol",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
  { name: "P-19 Redeemer", warbond: "free", type: "Pistol",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Steeled Veterans
  { name: "P-4 Senator", warbond: "steeled-veterans", type: "Revolver",
          light: "green", medium: "green", heavy: "green",
          bugnest: "red", charger: "yellow", biletitan: "yellow",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
          
        // Cutting Edge
  { name: "Las-7 Dagger", warbond: "cutting-edge", type: "Special",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Democratic Detonation
  { name: "GP-31 Grenade Pistol", warbond: "democratic-detonation", type: "Special",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Polar Patriots
  { name: "P-113 Verdict", warbond: "polar-patriots", type: "Pistol",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
          
        // Viper Commandos
  { name: "SG-22 Bushwhacker", warbond: "viper-commandos", type: "Special",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
          
        // Freedom's Flame
  { name: "P-72 Crisper", warbond: "freedom-flame", type: "Special",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
          
        // Chemical Agents
  { name: "P-11 Stim Pistol", warbond: "chemical-agents", type: "Special",
          light: "red", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Truth Enforcers
  { name: "Plas-15 Loyalist", warbond: "truth-enforcers", type: "Special",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Urban Legends
  { name: "CQC-19 Stun Lance", warbond: "urban-legends", type: "Melee",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
          
        // Servants of Freedom
  { name: "GP-31 Ultimatum", warbond: "servants-freedom", type: "Special",
          light: "green", medium: "green", heavy: "green",
          bugnest: "green", charger: "green", biletitan: "green",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
          
        // Masters of Ceremony
  { name: "CQC-2 Saber", warbond: "masters-ceremony", type: "Melee",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
          
        // Control Group Premium Warbond - Placeholder entries (details TBD)
  { name: "PLAS-45 Epoch", warbond: "control-group", type: "Support",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        
        // ODST Legendary Warbond (Halo Crossover - 1,500 SC)
  { name: "M6C/SOCOM Pistol", warbond: "odst", type: "Pistol",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        
        // Dust Devils Premium Warbond - Placeholder entries (details TBD)
  { name: "AR-2 Coyote", warbond: "dust-devils", type: "Assault Rifle",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Borderline Justice
  { name: "Las-58 Talon", warbond: "borderline-justice", type: "Special",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
  { name: "TED-63 Dynamite", warbond: "borderline-justice", type: "Special",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Super Store Items
  { name: "CQC-30 Stun Baton", warbond: "free", type: "Melee",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
  { name: "CQC-5 Combat Hatchet", warbond: "free", type: "Melee",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" }
    ],
    grenade: [
        // Free/Base Game
  { name: "G-12 High Explosive", warbond: "free", type: "Standard",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
  { name: "G-16 Impact", warbond: "free", type: "Standard",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
  { name: "G-6 Frag", warbond: "free", type: "Standard",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
  { name: "G-3 Smoke", warbond: "free", type: "Standard",
          light: "red", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Steeled Veterans
  { name: "G-10 Incendiary", warbond: "steeled-veterans", type: "Standard",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
          
        // Cutting Edge
  { name: "G-23 Stun", warbond: "cutting-edge", type: "Special",
          light: "yellow", medium: "yellow", heavy: "yellow",
          bugnest: "yellow", charger: "yellow", biletitan: "yellow",
          factory: "yellow", hulk: "yellow", strider: "yellow",
          warpship: "yellow", harvester: "yellow", voteless: "green" },
          
        // Democratic Detonation
  { name: "G-123 Thermite", warbond: "democratic-detonation", type: "Standard",
          light: "green", medium: "yellow", heavy: "green",
          bugnest: "yellow", charger: "green", biletitan: "green",
          factory: "yellow", hulk: "green", strider: "green",
          warpship: "yellow", harvester: "green", voteless: "yellow" },
          
        // Polar Patriots
  { name: "G-13 Incendiary Impact", warbond: "polar-patriots", type: "Standard",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
          
        // Viper Commandos
  { name: "K-2 Throwing Knife", warbond: "viper-commandos", type: "Special",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Chemical Agents
  { name: "G-4 Gas", warbond: "chemical-agents", type: "Special",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Servants of Freedom
  { name: "G-50 Seeker", warbond: "servants-freedom", type: "Special",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
          
        // Masters of Ceremony
  { name: "G-142 Pyrotech", warbond: "masters-ceremony", type: "Special",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
          
        // Control Group Premium Warbond - Placeholder entries (details TBD)
  { name: "LIFT-182 Warp Pack", warbond: "control-group", type: "Backpack", slot: "backpack",
          light: "red", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "red" },
  { name: "G-31 Arc", warbond: "control-group", type: "Throwable", slot: "grenade",
    light: "green", medium: "yellow", heavy: "red",
    bugnest: "green", charger: "yellow", biletitan: "red",
    factory: "green", hulk: "yellow", strider: "red",
    warpship: "green", harvester: "red", voteless: "green" },
        
        // Dust Devils Premium Warbond - Placeholder entries (details TBD)
  { name: "S-11 Speargun", warbond: "dust-devils", type: "Support", slot: "support",
    light: "green", medium: "green", heavy: "red",
    bugnest: "green", charger: "yellow", biletitan: "red",
    factory: "green", hulk: "yellow", strider: "yellow",
    warpship: "green", harvester: "yellow", voteless: "green" },
  // Dust Devils stratagems: ensure support stratagems are present as selectable stratagem entries where applicable
  { name: "MS-11 Solo Silo", warbond: "dust-devils", slot: "support", type: "Support",
    light: "green", medium: "green", heavy: "green",
    bugnest: "green", charger: "green", biletitan: "green",
    factory: "green", hulk: "green", strider: "green",
    warpship: "green", harvester: "green", voteless: "green" },
  { name: "EAT-700 Expendable Napalm", warbond: "dust-devils", type: "Support", slot: "support",
    light: "green", medium: "yellow", heavy: "red",
    bugnest: "green", charger: "yellow", biletitan: "red",
    factory: "green", hulk: "yellow", strider: "red",
    warpship: "green", harvester: "red", voteless: "green" },
  { name: "G-7 Pineapple", warbond: "dust-devils", type: "Special", slot: "none",
    light: "green", medium: "yellow", heavy: "red",
    bugnest: "green", charger: "yellow", biletitan: "red",
    factory: "green", hulk: "yellow", strider: "red",
    warpship: "green", harvester: "red", voteless: "green" }
    ],
    stratagem: [
        // Support Weapons - Free/Base Game
        { name: "EAT-17 Expendable Anti-Tank", warbond: "free", slot: "support",
          light: "yellow", medium: "green", heavy: "green",
          bugnest: "red", charger: "green", biletitan: "green",
          factory: "red", hulk: "green", strider: "green",
          warpship: "red", harvester: "green", voteless: "yellow" },
        { name: "GR-8 Recoilless Rifle", warbond: "free", slot: "support+backpack",
          light: "yellow", medium: "green", heavy: "green",
          bugnest: "red", charger: "green", biletitan: "green",
          factory: "red", hulk: "green", strider: "green",
          warpship: "red", harvester: "green", voteless: "yellow" },
        { name: "FLAM-40 Flamethrower", warbond: "free", slot: "support",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
        { name: "AC-8 Autocannon", warbond: "free", slot: "support+backpack",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "RS-422 Railgun", warbond: "free", slot: "support",
          light: "yellow", medium: "green", heavy: "green",
          bugnest: "red", charger: "green", biletitan: "green",
          factory: "red", hulk: "green", strider: "green",
          warpship: "red", harvester: "green", voteless: "yellow" },
        { name: "LAS-98 Laser Cannon", warbond: "free", slot: "support",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
        { name: "LAS-99 Quasar Cannon", warbond: "free", slot: "support",
          light: "yellow", medium: "green", heavy: "green",
          bugnest: "red", charger: "green", biletitan: "green",
          factory: "red", hulk: "green", strider: "green",
          warpship: "red", harvester: "green", voteless: "yellow" },
        { name: "MG-43 Machine Gun", warbond: "free", slot: "support",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
        { name: "APW-1 Anti-Materiel Rifle", warbond: "free", slot: "support",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
        { name: "M-105 Stalwart", warbond: "free", slot: "support",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "ARC-3 Arc Thrower", warbond: "free", slot: "support",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "GL-21 Grenade Launcher", warbond: "free", slot: "support",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
  // Support Weapons - Cutting Edge
  // (Removed duplicate stratagem entry for LAS-16 Sickle; LAS-16 is a primary weapon)
          
        // Support Weapons - Democratic Detonation
        { name: "airburst Rocket Launcher", warbond: "democratic-detonation", slot: "support",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Support Weapons - Polar Patriots
        { name: "MG-206 Heavy Machine Gun", warbond: "polar-patriots", slot: "support",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
          
  // Support Weapons - Freedom's Flame  
  // (Removed duplicate stratagem entry for FLAM-66 Torcher; FLAM-66 is a primary weapon)
          
        // Orbital Stratagems - Free/Base Game
        { name: "Orbital Precision Strike", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "green",
          bugnest: "green", charger: "green", biletitan: "yellow",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "Orbital Airburst Strike", warbond: "free", slot: "none",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "Orbital 120MM HE Barrage", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "yellow",
          bugnest: "green", charger: "green", biletitan: "yellow",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "Orbital 380MM HE Barrage", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "green",
          bugnest: "green", charger: "green", biletitan: "green",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "Orbital Walking Barrage", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "green",
          bugnest: "green", charger: "green", biletitan: "green",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "Orbital Laser", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "green",
          bugnest: "green", charger: "green", biletitan: "green",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "Orbital Railcannon Strike", warbond: "free", slot: "none",
          light: "yellow", medium: "green", heavy: "green",
          bugnest: "red", charger: "green", biletitan: "green",
          factory: "red", hulk: "green", strider: "green",
          warpship: "red", harvester: "green", voteless: "yellow" },
          
        // Eagle Stratagems - Free/Base Game
        { name: "Eagle Frag Bomb", warbond: "free", slot: "none",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "Eagle Airstrike", warbond: "free", slot: "none",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "Eagle Cluster Bomb", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "yellow",
          bugnest: "green", charger: "green", biletitan: "yellow",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "Eagle Napalm Airstrike", warbond: "free", slot: "none",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "Eagle Smoke Strike", warbond: "free", slot: "none",
          light: "red", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "Eagle 110MM Rocket Pods", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "yellow",
          bugnest: "green", charger: "green", biletitan: "yellow",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "Eagle 500kg Bomb", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "green",
          bugnest: "green", charger: "green", biletitan: "green",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
          
        // Defensive Stratagems - Free/Base Game
        { name: "A/MG-43 Machine Gun Sentry", warbond: "free", slot: "none",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
        { name: "A/G-16 Gatling Sentry", warbond: "free", slot: "none",
          light: "green", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "A/M-12 Mortar Sentry", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "yellow",
          bugnest: "green", charger: "green", biletitan: "yellow",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "A/AC-8 Autocannon Sentry", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "A/MLS-4X Rocket Sentry", warbond: "free", slot: "none",
          light: "green", medium: "green", heavy: "green",
          bugnest: "green", charger: "green", biletitan: "yellow",
          factory: "green", hulk: "green", strider: "green",
          warpship: "green", harvester: "green", voteless: "green" },
        { name: "A/ARC-3 Tesla Tower", warbond: "free", slot: "none",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "MD-6 Anti-Personnel Minefield", warbond: "free", slot: "none",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
        { name: "MD-I4 Incendiary Mines", warbond: "free", slot: "none",
          light: "green", medium: "red", heavy: "red",
          bugnest: "green", charger: "red", biletitan: "red",
          factory: "green", hulk: "red", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
        { name: "A/M-23 EMS Mortar Sentry", warbond: "free", slot: "none",
          light: "yellow", medium: "yellow", heavy: "yellow",
          bugnest: "yellow", charger: "yellow", biletitan: "yellow",
          factory: "yellow", hulk: "yellow", strider: "yellow",
          warpship: "yellow", harvester: "yellow", voteless: "green" },
          
  // Supply Stratagems - Free/Base Game (moved default-granted items to top-level grantedStratagems)
        
        // Backpacks - Free/Base Game
        { name: "B-1 Supply Pack", warbond: "free", slot: "backpack",
          light: "red", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
        { name: "SH-20 Ballistic Shield Backpack", warbond: "free", slot: "backpack",
          light: "yellow", medium: "yellow", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
        { name: "SH-32 Shield Generator Pack", warbond: "free", slot: "backpack",
          light: "red", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "red" },
        { name: "LIFT-850 Jump Pack", warbond: "free", slot: "backpack",
          light: "red", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Cutting Edge Stratagems
        { name: "A/LAS-5 Laser Cannon Sentry", warbond: "cutting-edge", slot: "none",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "red", hulk: "yellow", strider: "yellow",
          warpship: "red", harvester: "yellow", voteless: "green" },
          
        // Steeled Veterans Stratagems
        { name: "Orbital Gas Strike", warbond: "steeled-veterans", slot: "none",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "Orbital EMS Strike", warbond: "steeled-veterans", slot: "none",
          light: "yellow", medium: "yellow", heavy: "yellow",
          bugnest: "yellow", charger: "yellow", biletitan: "yellow",
          factory: "yellow", hulk: "yellow", strider: "yellow",
          warpship: "yellow", harvester: "yellow", voteless: "green" },
        { name: "Orbital Smoke Barrage", warbond: "steeled-veterans", slot: "none",
          light: "red", medium: "red", heavy: "red",
          bugnest: "red", charger: "red", biletitan: "red",
          factory: "red", hulk: "red", strider: "red",
          warpship: "red", harvester: "red", voteless: "green" },
          
        // Democratic Detonation Stratagems
        { name: "MD-17 Anti-Tank Mines", warbond: "democratic-detonation", slot: "none",
          light: "yellow", medium: "green", heavy: "green",
          bugnest: "red", charger: "green", biletitan: "green",
          factory: "red", hulk: "green", strider: "green",
          warpship: "red", harvester: "green", voteless: "yellow" },
          
        // Freedom's Flame Stratagems
        { name: "Orbital Napalm Barrage", warbond: "freedom-flame", slot: "none",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
          
        // Control Group Premium Warbond - Placeholder entries (details TBD)
        { name: "A/LAS-98 Laser Sentry", warbond: "control-group", slot: "support", type: "Sentry",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },

        // Force of Law Premium Warbond - stratagems
        { name: "GL-52 De-Escalator", warbond: "force-of-law", slot: "support",
          light: "green", medium: "green", heavy: "red",
          bugnest: "red", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "AX/ARC-3 \"Guard Dog\" K-9", warbond: "force-of-law", slot: "backpack", type: "Backpack",
          light: "green", medium: "green", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "yellow",
          warpship: "green", harvester: "yellow", voteless: "green" },
        { name: "G-109 Urchin", warbond: "force-of-law", type: "Throwable", slot: "grenade",
          light: "green", medium: "yellow", heavy: "red",
          bugnest: "green", charger: "yellow", biletitan: "red",
          factory: "green", hulk: "yellow", strider: "red",
          warpship: "green", harvester: "red", voteless: "green" },
        
  // Dust Devils Premium Warbond - stratagems handled above; grenade entries kept separately
    ]
};

// Export for Node.js compatibility
if (typeof module !== 'undefined') {
    module.exports = weapons;
}

// Make available globally for browser
if (typeof window !== 'undefined') {
    window.weapons = weapons;
}